### ISSUE TITLE
Your library breaks on devel version of SBCL

### ISSUE THREAD

**Issue by bigos** [andy128k/cl-gobject-introspection#100]
https://sourceforge.net/p/sbcl/mailman/message/58773714/

this line seems to cause problems
https://github.com/andy128k/cl-gobject-introspection/blob/6b30d05e189407ee825e56d8ec6951c13e6bfb23/src/init.lisp#L146

I wonder how sbcl will respond to that, and at this point, I do not know what else I may need to suggest.

The error is:
[Lock on package SB-EXT violated when interning SET-FLOATING-POINT-MODES while ; in package GIR.]

**Comment by bigos** [comment]
https://github.com/andy128k/cl-gobject-introspection/pull/101 
somebody added a pull request

**Comment by andy128k** [comment]
#101 is merged
